language: python
python:
    - "2.7"
env:
    matrix:
        - TOXENV=py27
        - TOXENV=style
        - TOXENV=docs
install:
    - pip install tox
script:
    tox
notifications:
    irc:
        channels:
            - "irc.mozilla.org#mds"
        on_success: always
        on_failure: always
        use_notice: true
